# Generated by Django 4.1.4 on 2023-02-23 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("donor", "0001_initial"),
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stored",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blood_type", models.CharField(max_length=50)),
                ("unites_number", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="RequestBllod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pat_name", models.CharField(max_length=50)),
                ("pat_age", models.PositiveIntegerField()),
                ("blood_type", models.CharField(max_length=50)),
                ("unites_number", models.PositiveIntegerField(default=0)),
                ("purpose", models.CharField(max_length=300)),
                ("status", models.CharField(default="Pending", max_length=40)),
                ("date_req", models.DateField(auto_now=True)),
                (
                    "donner_request",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="donor.donor",
                    ),
                ),
                (
                    "patient_request",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                    ),
                ),
            ],
        ),
    ]
